// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotfjbmdllhvqrsyxxhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdGZqYm1kbGxodnFyc3l4eGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDQxMjksImV4cCI6MjA2MDQ4MDEyOX0.strhdCJLpkURtRuO0VrCiFuf0IJ2ZwrAn8M8Y8umANY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);